services:
  postgres:
    image: postgres:15-alpine
    container_name: postgreSQL
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: WarehouseDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432 
    healthcheck:
      test: [CMD-SHELL, pg_isready -U user -d DrinksMachineDb]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: